export const FETCH_INTERVALS = 'intervals/FETCH_INTERVALS';
export const TOGGLE_INTERVAL_COMPLETED = 'intervals/TOGGLE_INTERVAL_COMPLETED';
export const FETCH_INTERVALS_BEGIN = 'intervals/FETCH_INTERVALS_BEGIN';