export const CHANGE_COUNTER_DETAILS = 'CHANGE_COUNTER_DETAILS';
export const CHANGE_COUNTER_DETAILS_TYPE = 'CHANGE_COUNTER_DETAILS_TYPE';
export const ADD_INTERVAL = 'ADD_INTERVAL';

export const FETCH_INTERVALS = 'FETCH_INTERVALS';
export const TOGGLE_INTERVAL_COMPLETED = 'TOGGLE_INTERVAL_COMPLETED';
export const FETCH_INTERVALS_BEGIN = 'FETCH_INTERVALS_BEGIN';

export const USER_SIGNED_IN = 'USER_SIGNED_IN';
export const USER_SIGNED_OUT = 'USER_SIGNED_OUT';
